#!/usr/bin/env sh
set -e

DIR=$(cd "$(dirname "${0}")"; pwd)


basename="${0##*/}"
triplet="${basename##pkgconf-wrapper\.}"

case "${triplet}" in
  amd64|x86_64*)
    triplet='x86_64-w64-mingw32'
    ;;
  arm64|aarch64*)
    triplet='aarch64-w64-mingw32'
    ;;
esac

PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR}:${DIR}/${triplet}/lib"
export PKG_CONFIG_LIBDIR

if command -v pkgconf >/dev/null 2>&1 ; then
  exec pkgconf "$@"
else
  exec pkg-config "$@"
fi
