#!/usr/bin/env sh
set -e

DIR=$(cd "$(dirname "${0}")"; pwd)


basename="${0##*/}"
triplet="${basename##pkgconf-wrapper\.}"

PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR}:${DIR}/${triplet}/usr/lib"
PKG_CONFIG_LIBDIR="${PKG_CONFIG_LIBDIR}:${DIR}/${triplet}/lib"
export PKG_CONFIG_LIBDIR

if command -v pkgconf >/dev/null 2>&1 ; then
  exec pkgconf "$@"
else
  exec pkg-config "$@"
fi
