if(_LINUX_CROSS_TOOLCHAIN_INCLUDED)
  return()
endif()
set(_LINUX_CROSS_TOOLCHAIN_INCLUDED true)


get_filename_component(fext
  "${CMAKE_CURRENT_LIST_FILE}" LAST_EXT
)
string(REGEX REPLACE "^\\." "" fext "${fext}")
string(REGEX MATCHALL "[^-]+" archinfo "${fext}")
list(GET archinfo 0 arch)
list(GET archinfo 1 info)


set(triplet)
set(extra_flags)
if(arch STREQUAL "amd64")
  set(triplet "x86_64-pc-linux")
  set(extra_flags "-march=x86-64-v2")
elseif(arch STREQUAL "arm64")
  set(triplet "aarch64-unknown-linux")
  set(extra_flags "-march=armv8-a")
elseif(arch STREQUAL "armv7")
  set(triplet "arm-unknown-linux")
  set(extra_flags "-march=armv7-a" "-mfpu=neon-vfpv4" "-mfloat-abi=hard")
else()
  message(FATAL_ERROR "Unsupported ARCH: ${arch}")
endif()
set(sysroot_triplet "${triplet}-${info}")
set(sysroot "${CMAKE_CURRENT_LIST_DIR}/${sysroot_triplet}")

set(dynamic_linker)
if("${arch}-${info}" STREQUAL "arm64-gnu")
  set(dynamic_linker "/lib/ld-linux-aarch64.so.1")
elseif("${arch}-${info}" STREQUAL "amd64-gnu")
  set(dynamic_linker "/lib64/ld-linux-x86-64.so.2")
elseif("${arch}-${info}" STREQUAL "armv7-gnueabihf")
  set(dynamic_linker "/lib/ld-linux-armhf.so.3")
elseif("${arch}-${info}" STREQUAL "arm64-musl")
  set(dynamic_linker "/lib/ld-musl-aarch64.so.1")
elseif("${arch}-${info}" STREQUAL "amd64-musl")
  set(dynamic_linker "/lib/ld-musl-x86_64.so.1")
elseif("${arch}-${info}" STREQUAL "armv7-musleabihf")
  set(dynamic_linker "/lib/ld-musl-armhf.so.1")
elseif("${arch}-${info}" STREQUAL "armv7-uclibceabihf")
  set(dynamic_linker "/lib/ld-uClibc.so.1")
else()
  message(FATAL_ERROR "Unsupported INFO: ${info}")
endif()



set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "${arch}")
set(CMAKE_CROSSCOMPILING TRUE)
set(CMAKE_SYSROOT "${sysroot}")
set(CMAKE_C_COMPILER   "clang"   "--target=${triplet}" "--gcc-toolchain=${sysroot}/usr" "--gcc-triple=${sysroot_triplet}" ${extra_flags})
set(CMAKE_CXX_COMPILER "clang++" "--target=${triplet}" "--gcc-toolchain=${sysroot}/usr" "--gcc-triple=${sysroot_triplet}" ${extra_flags})
set(CMAKE_ASM_COMPILER "${CMAKE_C_COMPILER}")
set(CMAKE_LINKER_TYPE  "LLD")
set(CMAKE_EXE_LINKER_FLAGS    "-Wl,--dynamic-linker=${dynamic_linker}")
set(CMAKE_MODULE_LINKER_FLAGS "-Wl,--dynamic-linker=${dynamic_linker}")
set(CMAKE_SHARED_LINKER_FLAGS "-Wl,--dynamic-linker=${dynamic_linker}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PKG_CONFIG_EXECUTABLE "${CMAKE_CURRENT_LIST_DIR}/pkgconf-wrapper.${arch}-${info}" CACHE FILEPATH "pkgconf executable")
