name: _buildx_cross_sysroot_linux_generator
on:
  workflow_call:
    inputs:
      SYSROOT_LINUX_HEADER_UAPI:
        required: true
        type: string
      SYSROOT_LIBSTDCXX_GCC_VER:
        required: true
        type: string

jobs:
  _buildx:
    strategy:
      matrix:
        include:
          - target: target-ct-amd64-glibc
          - target: target-ct-arm64-glibc
          - target: target-ct-armhf-glibc
          - target: target-ct-amd64-musl
          - target: target-ct-arm64-musl
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Build Cross Sysroot - ${{ matrix.target }}
        uses: docker/build-push-action@v6
        with:
          pull: true
          push: false
          context: cross-sysroot-linux-generator
          target: ${{ matrix.target }}
          build-args: |
            SYSROOT_LINUX_HEADER_UAPI=${{ inputs.SYSROOT_LINUX_HEADER_UAPI }}
            SYSROOT_LIBSTDCXX_GCC_VER=${{ inputs.SYSROOT_LIBSTDCXX_GCC_VER }}
          tags: |
            ${{ github.workflow }}:${{ github.sha }}
      - name: Catch Cross Sysroot - ${{ matrix.target }}
        run: |
          docker images
          docker create --name sysroot-gen ${{ github.workflow }}:${{ github.sha }}
          docker cp -a sysroot-gen:/crosstool .; docker rm sysroot-gen
      - name: Push Cross Sysroot - ${{ matrix.target }}
        uses: actions/upload-artifact@v4
        with:
          name: crosstool-linux${{ inputs.SYSROOT_LINUX_HEADER_UAPI }}-gcc${{ inputs.SYSROOT_LIBSTDCXX_GCC_VER }}-${{ matrix.target }}
          path: crosstool
          if-no-files-found: error
