name: _buildx_cross_sysroot_linux_generator
on:
  workflow_call:
    inputs:
      SYSROOT_LINUX_HEADER_UAPI:
        required: true
        type: string
      SYSROOT_LIBSTDCXX_GCC_VER:
        required: true
        type: string

env:
  GH_TOKEN: ${{ github.token }}
  GH_OSSUTIL_AK: ${{ secrets.GH_OSSUTIL_AK }}
  GH_OSSUTIL_SK: ${{ secrets.GH_OSSUTIL_SK }}
  GH_OSSUTIL_BUCKET: ${{ secrets.GH_OSSUTIL_BUCKET }}
  GH_OSSUTIL_REGION: ${{ secrets.GH_OSSUTIL_REGION }}
  GH_OSSUTIL_PKGS: ${{ secrets.GH_OSSUTIL_PKGS }}
  GH_OSSUTIL_CNAME: ${{ secrets.GH_OSSUTIL_CNAME }}

jobs:
  _buildx:
    strategy:
      matrix:
        include:
          - target: target-ct-amd64-glibc
          - target: target-ct-arm64-glibc
          - target: target-ct-armhf-glibc
          - target: target-ct-amd64-musl
          - target: target-ct-arm64-musl
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}
    env:
      _archive_: crosstool-linux${{ inputs.SYSROOT_LINUX_HEADER_UAPI }}-gcc${{ inputs.SYSROOT_LIBSTDCXX_GCC_VER }}-${{ matrix.target }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: Build Cross Sysroot - ${{ matrix.target }}
        uses: docker/build-push-action@v6
        with:
          pull: true
          push: false
          load: true
          context: cross-sysroot-linux-generator
          target: ${{ matrix.target }}
          build-args: |
            SYSROOT_LINUX_HEADER_UAPI=${{ inputs.SYSROOT_LINUX_HEADER_UAPI }}
            SYSROOT_LIBSTDCXX_GCC_VER=${{ inputs.SYSROOT_LIBSTDCXX_GCC_VER }}
          tags: |
            ${{ github.workflow }}:${{ github.sha }}
      - name: Catch Cross Sysroot
        run: |
          docker images
          docker create --name sysroot-gen ${{ github.workflow }}:${{ github.sha }}
          docker cp -a sysroot-gen:/crosstool .; docker rm sysroot-gen

          # keep file permissions and case sensitivity
          tar -cvf ${{ env._archive_ }}.tar crosstool
      - name: Push Cross Sysroot
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env._archive_ }}
          path: ${{ env._archive_ }}.tar
          if-no-files-found: error
      - name: Commit to Pre-compiled Storage
        if: ${{ github.event_name == 'push' }}
        run: |
          zip -ry "${{ env._archive_ }}.zip" crosstool
          ./.github/oss_v4.py push "${{ env._archive_ }}.zip" "${{ env._archive_ }}.zip"
