name: cgo-openwrt-mt7622
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cgo-openwrt-mt7622.yml'
      - 'cgo-openwrt-mt7622/**'
      - '!cgo-openwrt-mt7622/README.md'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cgo-openwrt-mt7622.yml'
      - 'cgo-openwrt-mt7622/**'
      - '!cgo-openwrt-mt7622/README.md'

jobs:
  build:
    if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
