name: cgo-linux-g217
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cgo-linux-g217.yml'
      - 'cgo-linux-g217/Dockerfile'
      - 'cgo-linux-g217/*.repo'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cgo-linux-g217.yml'
      - 'cgo-linux-g217/Dockerfile'
      - 'cgo-linux-g217/*.repo'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: linux/amd64,linux/arm64
