name: cross-sysroot-linux310-gcc7
on:
  push:
    branches:
      - main
    paths:
      - '.github/rclone.conf.tmpl'
      - '.github/rclone.py'
      - '.github/workflows/_buildx_cross_sysroot_linux_generator.yml'
      - '.github/workflows/cross-sysroot-linux310-gcc7-generator.yml'
      - 'cross-sysroot-linux-generator/.config.linux310.gcc7*.ini'
      - 'cross-sysroot-linux-generator/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/rclone.conf.tmpl'
      - '.github/rclone.py'
      - '.github/workflows/_buildx_cross_sysroot_linux_generator.yml'
      - '.github/workflows/cross-sysroot-linux310-gcc7-generator.yml'
      - 'cross-sysroot-linux-generator/.config.linux310.gcc7*.ini'
      - 'cross-sysroot-linux-generator/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx_cross_sysroot_linux_generator.yml
    with:
      SYSROOT_LINUX_HEADER_UAPI: "310"
      SYSROOT_LIBSTDCXX_GCC_VER: "7"
