name: cross-sysroot-linux-arm64-musl
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cross-sysroot-linux-arm64-musl.yml'
      - 'cross-sysroot-linux-generator/.config.linux.musl.arm64'
      - 'cross-sysroot-linux-generator/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cross-sysroot-linux-arm64-musl.yml'
      - 'cross-sysroot-linux-generator/.config.linux.musl.arm64'
      - 'cross-sysroot-linux-generator/Dockerfile'

jobs:
  build:
    if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      context: 'cross-sysroot-linux-generator'
      latest: false
      target: 'target-ct-arm64-musl'
