name: cross-sysroot-linux310-gcc7-generator
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cross-sysroot-linux310-gcc7-generator.yml'
      - 'cross-sysroot-linux-generator/.config.linux310.gcc7*.ini'
      - 'cross-sysroot-linux-generator/Dockerfile'
      - 'cross-sysroot-linux-generator/organize_sysroot.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/cross-sysroot-linux310-gcc7-generator.yml'
      - 'cross-sysroot-linux-generator/.config.linux310.gcc7*.ini'
      - 'cross-sysroot-linux-generator/Dockerfile'
      - 'cross-sysroot-linux-generator/organize_sysroot.sh'

jobs:
  build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
          - armhf
        libc:
          - musl
          - gnu
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      is_push: false
      context: cross-sysroot-linux-generator
      build-args: |
        SYSROOT_LINUX_HEADER_UAPI=310
        SYSROOT_LIBSTDCXX_GCC_VER=7
        SYSROOT_TARGET_ARCH=${{ matrix.arch }}
        SYSROOT_TARGET_LIBC=${{ matrix.libc }}
        COMMIT_LINUX_SYSROOT=${{ github.event_name == 'workflow_dispatch' }}
