name: cross-sysroot-linux419-gcc4
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/rclone.conf.tmpl'
      - '.github/rclone.py'
      - '.github/workflows/_buildx_cross_sysroot_linux_generator.yml'
      - '.github/workflows/cross-sysroot-linux419-gcc4-generator.yml'
      - 'cross-sysroot-linux-generator/.config.linux419.gcc4*.ini'
      - 'cross-sysroot-linux-generator/Dockerfile'
      - 'cross-sysroot-linux-generator/organize_sysroot.sh'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx_cross_sysroot_linux_generator.yml
    with:
      SYSROOT_LINUX_HEADER_UAPI: "419"
      SYSROOT_LIBSTDCXX_GCC_VER: "4"
