name: ct-linux419-arm64-musl
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/ct-linux419-arm64-musl.yml'
      - 'cross-toolchain-linux-basic/.config.linux419.musl.arm64'
      - 'cross-toolchain-linux-basic/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/ct-linux419-arm64-musl.yml'
      - 'cross-toolchain-linux-basic/.config.linux419.musl.arm64'
      - 'cross-toolchain-linux-basic/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      build-args: |
        LINUX_UAPI_VERSION=419
      context: 'cross-toolchain-linux-basic'
      target: 'target-ct-arm64-musl'
