name: ct-linux310-amd64-musl
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/ct-linux310-amd64-musl.yml'
      - 'cross-toolchain-linux-basic/.config.linux310.musl.amd64'
      - 'cross-toolchain-linux-basic/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/ct-linux310-amd64-musl.yml'
      - 'cross-toolchain-linux-basic/.config.linux310.musl.amd64'
      - 'cross-toolchain-linux-basic/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      build-args: |
        LINUX_UAPI_VERSION=310
      context: 'cross-toolchain-linux-basic'
      target: 'target-ct-amd64-musl'
