name: ct-linux310
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/ct-linux310.yml'
      - 'cross-toolchain-linux/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/ct-linux310.yml'
      - 'cross-toolchain-linux/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      build-args: |
        LINUX_UAPI_VERSION=310
      context: 'cross-toolchain-linux'
