name: linux419-cross
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/linux419-cross.yml'
      - 'linux-cross/.config.linux419.*'
      - 'linux-cross/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/linux419-cross.yml'
      - 'linux-cross/.config.linux419.*'
      - 'linux-cross/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      build-args: 'LINUX_UAPI_VERSION=419'
      context: 'linux-cross'
