name: mingw-cgo1.21
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-buildx.yml'
      - '.github/workflows/mingw-cgo1.21.yml'
      - 'mingw-cgo1.21/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/docker-buildx.yml'
      - '.github/workflows/mingw-cgo1.21.yml'
      - 'mingw-cgo1.21/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/docker-buildx.yml
    with:
      platforms: linux/amd64,linux/arm64
