name: mingw-cross-ucrt-cgo
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/mingw-cross-ucrt-cgo.yml'
      - 'mingw-cross-cgo/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/mingw-cross-ucrt-cgo.yml'
      - 'mingw-cross-cgo/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: linux/amd64,linux/arm64
      context: 'mingw-cross-cgo'
