name: mingw-cross-native
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/mingw-cross-native.yml'
      - 'mingw-cross-native/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/mingw-cross-native.yml'
      - 'mingw-cross-native/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: 'linux/amd64,linux/arm64'
