name: openwrt-cgo-mt7622
on:
  push:
    branches:
      - main
    paths:
      - 'openwrt-cgo-mt7622/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - 'openwrt-cgo-mt7622/Dockerfile'

jobs:
  build:
    uses: ./.github/workflows/docker-buildx.yml
    secrets: inherit
