name: openwrt-cgo-mt7622
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-buildx.yml'
      - '.github/workflows/openwrt-cgo-mt7622.yml'
      - 'openwrt-cgo-mt7622/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/docker-buildx.yml'
      - '.github/workflows/openwrt-cgo-mt7622.yml'
      - 'openwrt-cgo-mt7622/Dockerfile'

jobs:
  build:
    uses: ./.github/workflows/docker-buildx.yml
    secrets: inherit
