name: openwrt-cgo-mt7622
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/openwrt-cgo-mt7622.yml'
      - 'openwrt-cgo-mt7622/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/openwrt-cgo-mt7622.yml'
      - 'openwrt-cgo-mt7622/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
