name: serv-swaywm
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-swaywm.yml'
      - 'serv-swaywm/*'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      tagname: 'swaywm'
