name: xcaddy
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-xcaddy.yml'
      - 'serv-xcaddy/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-xcaddy.yml'
      - 'serv-xcaddy/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: linux/amd64,linux/arm64
      context: 'serv-xcaddy'
