name: serv-swaywm
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-swaywm.yml'
      - 'serv-swaywm/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-swaywm.yml'
      - 'serv-swaywm/Dockerfile'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      tagname: 'swaywm'
