name: serv-jellyfin
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-jellyfin.yml'
      - 'serv-jellyfin/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-jellyfin.yml'
      - 'serv-jellyfin/Dockerfile'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: 'linux/amd64,linux/arm64'
      tagname: 'jellyfin'
