name: serv-netatalk
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-netatalk.yml'
      - 'serv-netatalk/Dockerfile'
      - 'serv-netatalk/entrypoint.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/serv-netatalk.yml'
      - 'serv-netatalk/Dockerfile'
      - 'serv-netatalk/entrypoint.sh'

jobs:
  build:
    if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: 'linux/amd64,linux/arm64'
      tagname: 'netatalk'
