name: jellyfin
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/v-jellyfin.yml'
      - 'v-jellyfin/Dockerfile'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/v-jellyfin.yml'
      - 'v-jellyfin/Dockerfile'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: linux/amd64,linux/arm64
      context: 'v-jellyfin'
