name: xcaddy
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/xcaddy.yml'
      - 'xcaddy/**'
      - '!xcaddy/README.md'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/xcaddy.yml'
      - 'xcaddy/**'
      - '!xcaddy/README.md'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      platforms: linux/amd64,linux/arm64
